### ISSUE TITLE
the website is emtpy now

### ISSUE THREAD

**Issue by nanhaoliaodd01** [tpunt/php-internals-articles#2]
I open https://phpinternals.net this morning and cannot find any content on it.
They were there just two weeks ago.

**Comment by tpunt** [comment]
Hi! The [http version](http://phpinternals.net) works - I just haven't had the time yet to set it up to use https. Will get it done soon.

**Comment by tpunt** [comment]
I've updated the website link on this repo now. Also, check out the [tpunt/php-internals-docs](https://github.com/tpunt/php-internals-docs) repo for the raw docs and corresponding web application code.
